name: tiny_weather
description: "A tiny weather app with Flutter"
publish_to: 'none' 
version: 1.0.0+1
environment:
  sdk: ^3.7.0
dependencies:
  flutter:
    sdk: flutter
  uuid: ^4.5.1
  riverpod: ^2.6.1
  flutter_riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1
  freezed_annotation: ^3.0.0
  cupertino_icons: ^1.0.8
  go_router: ^14.8.1
  dio: ^5.7.0
  intl: ^0.19.0
  google_fonts: ^6.2.1
  fluttertoast: ^8.2.12
  timezone: ^0.10.0
  logger: ^2.5.0
  freezed: ^3.0.3
  path_provider: ^2.1.5
  hive_ce: ^2.10.1
  flutter_local_notifications: ^19.0.0
  permission_handler: ^11.4.0
  hive_ce_flutter: ^2.2.0
  cached_network_image: ^3.4.1
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  riverpod_generator: ^2.6.5
  hive_ce_generator: ^1.8.2
  flutter_lints: ^5.0.0
  custom_lint: ^0.7.5
  riverpod_lint: ^2.6.5
  go_router_builder: ^2.8.2
  build_runner: ^2.4.15
  build_verify: ^3.1.0
flutter:
  uses-material-design: true
analyzer:
  plugins:
    - custom_lint
custom_lint:
  rules:
    - provider_parameters
    - missing_provider_annotation
targets:
  $default:
    builder:
      go_router_builder:
        generate_for:
          - lib/router/*.dart
      hive_ce_generator:
        generate_for:
          - lib/local/model/*.dart
assets:
  - resources/*
  - resources/images/*
  - resources/fonts/*
  - resources/icons/*
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  #
  
  
